baseURL: "https://mad.lukasj.org"
languageCode: "da-dk"
title: "Livvy - Mad"
theme: "gochowdown"

menu:
  main:
    - name: Forside
      weight: 1
      url: /
    - name: Kategori
      weight: 2
      url: /category/
    - name: Køkken
      weight: 3
      url: /cuisine/
    - name: Tags
      weight: 4
      url: /tags/

taxonomies:
  category: category
  cuisine: cuisine
  tag: tags

